package io.flutter.plugins;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;
import io.flutter.Log;

import io.flutter.embedding.engine.FlutterEngine;
import io.flutter.embedding.engine.plugins.shim.ShimPluginRegistry;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
public final class GeneratedPluginRegistrant {
  private static final String TAG = "GeneratedPluginRegistrant";
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    ShimPluginRegistry shimPluginRegistry = new ShimPluginRegistry(flutterEngine);
    try {
      com.aloisdeniel.flutter.appcenter.AppcenterPlugin.registerWith(shimPluginRegistry.registrarFor("com.aloisdeniel.flutter.appcenter.AppcenterPlugin"));
    } catch(Exception e) {
      Log.e(TAG, "Error registering plugin appcenter, com.aloisdeniel.flutter.appcenter.AppcenterPlugin", e);
    }
    try {
      com.aloisdeniel.flutter.appcenter_analytics.AppcenterAnalyticsPlugin.registerWith(shimPluginRegistry.registrarFor("com.aloisdeniel.flutter.appcenter_analytics.AppcenterAnalyticsPlugin"));
    } catch(Exception e) {
      Log.e(TAG, "Error registering plugin appcenter_analytics, com.aloisdeniel.flutter.appcenter_analytics.AppcenterAnalyticsPlugin", e);
    }
    try {
      com.aloisdeniel.flutter.appcenter_crashes.AppcenterCrashesPlugin.registerWith(shimPluginRegistry.registrarFor("com.aloisdeniel.flutter.appcenter_crashes.AppcenterCrashesPlugin"));
    } catch(Exception e) {
      Log.e(TAG, "Error registering plugin appcenter_crashes, com.aloisdeniel.flutter.appcenter_crashes.AppcenterCrashesPlugin", e);
    }
  }
}
